title: "Agaram AI Labs"
description: "Enterprise AI solutions and intelligent automation for modern businesses"
url: "https://niranjanagaram.github.io"
baseurl: ""

author:
  name: "Niranjan Agaram"
  email: "niranjan@example.com"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default