title: "Niranjan's AI Insights"
description: "Lead Data Engineer specializing in AI development - from RAG systems to agentic AI workflows built on solid data foundations"
url: "https://niranjanagaram.github.io"
baseurl: ""

author:
  name: "Niranjan Agaram"
  email: "niranjanagaram@gmail.com"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Using custom styling instead of theme

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default